// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Customer struct {
	ID        int64
	Name      string
	Email     string
	Phone     sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}
